install:
  - go get github.com/Sirupsen/logrus
  - go get github.com/streadway/amqp
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega

script: go test -race

language: go

go:
  - 1.5
  - 1.6
  - tip
